# Generated by Django 5.2.5 on 2025-10-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DATSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dat_sequence',
            },
        ),
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255, verbose_name='Project')),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Architecture Dossier',
                'verbose_name_plural': 'Technical Architecture Dossiers',
                'db_table': 'dat_dat',
                'ordering': ['-created_at'],
            },
        ),
    ]
