# Generated by Django 5.2.9 on 2026-01-26 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'db_table': 'dat_application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nouvelle_demande', 'Nouvelle demande'), ('en_cours', 'En cours'), ('en_attente_de_revue', 'En Attente de revue'), ('valider', 'Valider'), ('refuse', 'Refusé'), ('reserve', 'Reserve')], default='nouvelle_demande', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_export_in_progress', models.BooleanField(default=False)),
                ('pdf_export_requested_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_export_requested_by_display', models.CharField(blank=True, max_length=255)),
                ('pdf_export_path', models.CharField(blank=True, default='', max_length=500)),
                ('pdf_export_content_type', models.CharField(blank=True, default='application/pdf', max_length=120)),
                ('pdf_export_size', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'dat_dat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DATHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Mise à jour'), ('status_changed', 'Changement de statut'), ('owner_changed', 'Changement de responsable'), ('section_updated', 'Section mise à jour'), ('responsible_validation', 'Validation référent'), ('deleted', 'Suppression')], max_length=32)),
                ('performed_by_display', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dat_history',
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DATPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100, verbose_name='Clé')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('data_type', models.CharField(choices=[('text', 'Texte'), ('long_text', 'Texte long'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('date', 'Date'), ('boolean', 'Booléen'), ('json', 'JSON'), ('url', 'Lien'), ('repeater', 'Tableau dynamique')], default='text', max_length=20, verbose_name='Type de donnée')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Partie de DAT',
                'verbose_name_plural': 'Parties de DAT',
                'db_table': 'dat_part',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DATPartEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Valeur de partie de DAT',
                'verbose_name_plural': 'Valeurs de parties de DAT',
                'db_table': 'dat_part_entry',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DATParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant du DAT',
                'verbose_name_plural': 'Participants du DAT',
                'db_table': 'dat_participant',
                'ordering': ['dat_id', 'role__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='DATPartPayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dat_part_payload',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='DATReserveHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('set', 'Mise en réserve'), ('cleared', 'Réserve levée')], default='set', max_length=20)),
                ('section_slug', models.SlugField(blank=True, max_length=100)),
                ('section_title', models.CharField(blank=True, max_length=200)),
                ('reserve_message', models.TextField(blank=True)),
                ('reserved_by_display', models.CharField(blank=True, max_length=255)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dat_reserve_history',
                'ordering': ['-reserved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DATSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Section de DAT',
                'verbose_name_plural': 'Sections de DAT',
                'db_table': 'dat_section',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DATSectionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=512, verbose_name='Chemin de stockage')),
                ('original_name', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('display_name', models.CharField(max_length=255, verbose_name='Nom affiché')),
                ('extension', models.CharField(max_length=16, verbose_name='Extension')),
                ('size', models.PositiveIntegerField(verbose_name='Taille')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Type de contenu')),
                ('uploaded_by_display', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Pièce jointe de section',
                'verbose_name_plural': 'Pièces jointes de section',
                'db_table': 'dat_section_attachment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DATSectionMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Metadata de section',
                'verbose_name_plural': 'Metadata de sections',
                'db_table': 'dat_section_metada',
            },
        ),
        migrations.CreateModel(
            name='DATSubSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identifiant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Sous-section de DAT',
                'verbose_name_plural': 'Sous-sections de DAT',
                'db_table': 'dat_sub_section',
                'ordering': ['order', 'id'],
            },
        ),
    ]
