# Generated by Django 5.2.9 on 2026-01-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dat', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='business_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='users.businessdirection', verbose_name='Direction métier'),
        ),
        migrations.AddField(
            model_name='dat',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dats', to='dat.application'),
        ),
        migrations.AddField(
            model_name='dat',
            name='business_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dats', to='users.businessdirection', verbose_name='Direction métier'),
        ),
        migrations.AddField(
            model_name='dat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dat',
            name='pdf_export_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dathistory',
            name='dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='dat.dat'),
        ),
        migrations.AddField(
            model_name='dathistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dat_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datpartentry',
            name='part',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dat.datpart', verbose_name='Partie'),
        ),
        migrations.AddField(
            model_name='datparticipant',
            name='dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dat.dat', verbose_name='DAT'),
        ),
        migrations.AddField(
            model_name='datparticipant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dat_participants', to='users.role', verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='datparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dat_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='datpartentry',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='dat.datpartpayload', verbose_name='Payload dédupliqué'),
        ),
        migrations.AddField(
            model_name='datreservehistory',
            name='dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_history_entries', to='dat.dat'),
        ),
        migrations.AddField(
            model_name='datreservehistory',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dat_reserve_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datsection',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='editable_dat_sections', to='users.role', verbose_name='Rôles autorisés'),
        ),
        migrations.AddField(
            model_name='datsection',
            name='dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dat.dat', verbose_name='DAT'),
        ),
        migrations.AddField(
            model_name='datsectionattachment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dat.datsection', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='datsectionattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dat_section_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par'),
        ),
        migrations.AddField(
            model_name='datsection',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='section', to='dat.datsectionmetadata', verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='datsubsection',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='editable_dat_sub_sections', to='users.role', verbose_name='Rôles autorisés'),
        ),
        migrations.AddField(
            model_name='datsubsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='dat.datsection', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='datpart',
            name='sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='dat.datsubsection', verbose_name='Sous-section'),
        ),
        migrations.AddConstraint(
            model_name='datparticipant',
            constraint=models.UniqueConstraint(fields=('dat', 'role'), name='dat_participant_unique_role_per_dat'),
        ),
        migrations.AddConstraint(
            model_name='datparticipant',
            constraint=models.UniqueConstraint(fields=('dat', 'user'), name='dat_participant_unique_user_per_dat'),
        ),
        migrations.AddIndex(
            model_name='datpartentry',
            index=models.Index(fields=['part'], name='dat_part_entry_part_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datsubsection',
            unique_together={('section', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='datpart',
            unique_together={('sub_section', 'key')},
        ),
    ]
