# Generated by Django 5.2.9 on 2026-02-09 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datparticipant",
            name="participant_type",
            field=models.CharField(
                choices=[("responsable", "Responsable"), ("executant", "Executant")],
                default="responsable",
                max_length=20,
                verbose_name="Type d'affectation",
            ),
        ),
        migrations.CreateModel(
            name="DATSectionResponsible",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis à jour le")),
                (
                    "dat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_responsibles",
                        to="dat.dat",
                        verbose_name="DAT",
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_assignment",
                        to="dat.datsection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_section_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable de section DAT",
                "verbose_name_plural": "Responsables de section DAT",
                "db_table": "dat_section_responsible",
                "ordering": ["section__order", "section__id"],
            },
        ),
    ]
