# Generated by Codex on 2025-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dat", "0003_application"),
    ]

    def assign_default_application(apps, schema_editor):
        Application = apps.get_model("dat", "Application")
        DAT = apps.get_model("dat", "DAT")

        default_application, _ = Application.objects.get_or_create(
            code="legacy-application",
            defaults={
                "name": "Legacy Application",
                "description": (
                    "Automatically created to backfill DAT records created before "
                    "applications became mandatory."
                ),
            },
        )

        DAT.objects.filter(application__isnull=True).update(application=default_application)

    def unassign_default_application(apps, schema_editor):
        Application = apps.get_model("dat", "Application")
        DAT = apps.get_model("dat", "DAT")

        try:
            default_application = Application.objects.get(code="legacy-application")
        except Application.DoesNotExist:
            return

        DAT.objects.filter(application=default_application).update(application=None)

        if not DAT.objects.filter(application=default_application).exists():
            default_application.delete()

    operations = [
        migrations.RunPython(assign_default_application, unassign_default_application),
        migrations.AlterField(
            model_name="dat",
            name="application",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="dats",
                to="dat.application",
            ),
        ),
    ]
