# Generated by Django 5.2.8 on 2025-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0003_remove_value_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datpartpayload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
