# Generated by Django 5.2.9 on 2026-02-17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dat", "0003_datparticipant_type_section_responsible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="datparticipant",
            name="participant_type",
            field=models.CharField(
                choices=[("responsable", "Responsable"), ("executant", "Normal")],
                default="responsable",
                max_length=20,
                verbose_name="Type d'affectation",
            ),
        ),
        migrations.CreateModel(
            name="DATAdmin",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                (
                    "dat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dat_admins",
                        to="dat.dat",
                        verbose_name="DAT",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_dats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur DAT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur DAT",
                "verbose_name_plural": "Administrateurs DAT",
                "db_table": "dat_admin",
                "ordering": ["dat_id", "created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("dat", "user"), name="dat_admin_unique_user_per_dat")
                ],
            },
        ),
        migrations.CreateModel(
            name="DATSectionParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis à jour le")),
                (
                    "dat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_participants",
                        to="dat.dat",
                        verbose_name="DAT",
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_assignment",
                        to="dat.datsection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_section_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant de section DAT",
                "verbose_name_plural": "Participants de section DAT",
                "db_table": "dat_section_participant",
                "ordering": ["section__order", "section__id"],
            },
        ),
    ]
