# Generated by Django 5.2.5 on 2025-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0004_dat_application_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='code',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
