# Generated by Django 5.2.9 on 2026-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0010_dat_section_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathistory',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Mise à jour'), ('status_changed', 'Changement de statut'), ('owner_changed', 'Changement de responsable'), ('section_updated', 'Section mise à jour'), ('responsible_validation', 'Validation référent'), ('deleted', 'Suppression')], max_length=32),
        ),
    ]
