# Generated by Django 5.2.9 on 2026-01-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0011_alter_dathistory_action'),
        ('dat', '0011_dat_section_metadata'),
    ]

    operations = [
    ]
