# Generated by Django 5.2.9 on 2026-01-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0012_merge_20260112_1633'),
        ('dat', '0012_section_metadata_fk'),
    ]

    operations = [
    ]
