# Generated by Django 5.2.5 on 2025-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0013_reset_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathistory',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Mise à jour'), ('status_changed', 'Changement de statut'), ('owner_changed', 'Changement de responsable'), ('section_updated', 'Section mise à jour'), ('deleted', 'Suppression')], max_length=32),
        ),
        migrations.AlterField(
            model_name='datpartentry',
            name='data_type',
            field=models.CharField(choices=[('text', 'Texte'), ('long_text', 'Texte long'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('date', 'Date'), ('boolean', 'Booléen'), ('json', 'JSON'), ('url', 'Lien'), ('repeater', 'Tableau dynamique')], default='text', max_length=20, verbose_name='Type de donnée'),
        ),
    ]
