# Generated by Django 5.2.9 on 2026-01-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0013_merge_20260112_1638'),
        ('dat', '0013_remove_dat_section_fields'),
    ]

    operations = [
    ]
