# Generated by Django 5.2.5 on 2025-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAT_id', models.CharField(max_length=10, unique=True)),
                ('Date_Creation', models.DateField(auto_now_add=True)),
                ('Date_MAJ', models.DateField(auto_now=True)),
                ('Version', models.CharField(verbose_name=10)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='UrbaID',
            field=models.CharField(default='00000', max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='dept',
            field=models.CharField(default='Non précisé', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('AR', 'Architecte Référent'), ('AT', 'Architecte Technique'), ('AL', 'Architecte Logiciel'), ('UR', 'Urbaniste'), ('AS', 'Analyste Cyber sécurité'), ('RS', 'Responsable SSI'), ('CS', 'Consultation')], default='CS', max_length=2),
        ),
    ]
