# Generated by Django 5.2.5 on 2025-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_dat_application_urbaid_person_dept_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvName', models.CharField(choices=[('PRD', 'Production'), ('PPD', 'Pré-production'), ('FRM', 'Formation'), ('INT', 'Intégration'), ('RCT', 'Recette'), ('QLF', 'Qualification')], default='PRD', max_length=3)),
                ('IsPROD', models.BooleanField(default=True)),
            ],
        ),
    ]
