# Generated by Django 5.2.5 on 2025-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_environnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
