# Generated by Django 5.2.5 on 2025-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_person_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposantLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLName', models.CharField(verbose_name=50)),
                ('CLDesc', models.CharField(verbose_name=200)),
            ],
        ),
    ]
