# Generated by Django 5.2.5 on 2025-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_composantlogiciel'),
    ]

    operations = [
        migrations.AddField(
            model_name='composantlogiciel',
            name='CLEditor',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='composantlogiciel',
            name='CLLicence',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='composantlogiciel',
            name='CLProduct',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='composantlogiciel',
            name='Derogation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='composantlogiciel',
            name='OOS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composantlogiciel',
            name='Version',
            field=models.CharField(default='0.0.0', max_length=20),
        ),
    ]
