# Generated by Django 5.2.5 on 2025-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_composantlogiciel_cleditor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composantlogiciel',
            old_name='OOS',
            new_name='OSS',
        ),
        migrations.AlterField(
            model_name='composantlogiciel',
            name='CLDesc',
            field=models.CharField(default="Description d'usage du composant logiciel", max_length=200),
        ),
        migrations.AlterField(
            model_name='composantlogiciel',
            name='CLName',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='EnvName',
            field=models.CharField(choices=[('PRD', 'Production'), ('PPD', 'Pré-production'), ('PRA', 'PRA'), ('PPR', 'Préprod PRA'), ('FRM', 'Formation'), ('INT', 'Intégration'), ('RCT', 'Recette'), ('QLF', 'Qualification')], default='PRD', max_length=3),
        ),
    ]
