# Generated by Django 5.2.5 on 2025-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_rename_oos_composantlogiciel_oss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Criticite',
            field=models.CharField(choices=[('STD', 'Standard'), ('SEN', 'Sensible'), ('CRT', 'Critique'), ('EXP', 'Expérimentation')], default='STD'),
        ),
        migrations.AddField(
            model_name='application',
            name='Description',
            field=models.CharField(default="description de la finalité de l'application", max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='EtatOperationnel',
            field=models.CharField(choices=[('ART', 'Arrêtée'), ('DEC', 'Décommissionnée'), ('PRD', 'En Production'), ('PLT', 'En phase pilote'), ('ABD', 'Abandonnée'), ('REL', 'En réalisation'), ('ETD', "En cours d'étude"), ('PRP', 'Proposé en cible')], default='PRD'),
        ),
        migrations.AddField(
            model_name='application',
            name='Exploitant',
            field=models.CharField(default='CDS Exploitation', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='LS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='Trigramme',
            field=models.CharField(default='NNN', max_length=3, unique=True),
        ),
    ]
