# Generated by Django 5.2.5 on 2025-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_application_criticite_application_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Trigramme',
            field=models.CharField(default='NNN', max_length=3),
        ),
    ]
