# Generated by Django 5.2.5 on 2025-08-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_alter_application_trigramme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Trigramme',
        ),
    ]
