# Generated by Django 5.2.4 on 2025-08-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_remove_application_trigramme'),
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
