# Generated by Django 5.2.4 on 2025-08-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0012_delete_datprocess_datprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datprocess',
            options={'permissions': [('can_view_nvdossier', 'Droits de visualisation de nvdossier')], 'verbose_name': 'DAT process'},
        ),
    ]
