# Generated by Django 5.2.4 on 2025-08-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0013_alter_datprocess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datprocess',
            options={'verbose_name': 'DAT process'},
        ),
    ]
