services:
  web:
    build:
      context: archifactory
    container_name: django
    ports:
      - "8000:8000"
    environment:
      RUN_MIGRATIONS: 1
    networks:
      - swag-network

networks:
  swag-network:
    external: true
