# Generated by Django 5.2.9 on 2026-02-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cintafactory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asyncjob',
            new_name='async_jobs_status_589bed_idx',
            old_name='async_jobs_status_d4f95f_idx',
        ),
        migrations.RenameIndex(
            model_name='asyncjob',
            new_name='async_jobs_resourc_6f1b89_idx',
            old_name='async_jobs_resourc_f85fed_idx',
        ),
        migrations.RenameIndex(
            model_name='asyncjob',
            new_name='async_jobs_idempot_2ff10e_idx',
            old_name='async_jobs_idempot_e23e04_idx',
        ),
        migrations.RenameIndex(
            model_name='asyncjob',
            new_name='async_jobs_created_45dde0_idx',
            old_name='async_jobs_created_1101da_idx',
        ),
    ]
