# Generated by Django 5.2.9 on 2026-01-26 12:36

import cintafactory.seaweedfs_storage
import diagrams.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawIODiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('png_paths', models.JSONField(blank=True, default=list, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('xml_file', models.FileField(blank=True, null=True, storage=cintafactory.seaweedfs_storage.SeaweedFSStorage(), upload_to=diagrams.models.drawio_upload_to)),
                ('xml_content_type', models.CharField(blank=True, default='application/xml', max_length=120)),
                ('xml_size', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=cintafactory.seaweedfs_storage.SeaweedFSStorage(), upload_to=diagrams.models.thumbnail_upload_to)),
                ('thumbnail_content_type', models.CharField(blank=True, default='image/png', max_length=120)),
                ('thumbnail_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'diagrams_diagram',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LikeC4Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('png_paths', models.JSONField(blank=True, default=list, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('png_path', models.CharField(blank=True, default='', max_length=500)),
                ('png_content_type', models.CharField(blank=True, default='image/png', max_length=200)),
                ('png_size', models.PositiveBigIntegerField(default=0)),
                ('png_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagrams_likec4file',
                'ordering': ['-updated_at'],
            },
        ),
    ]
