# Generated by Django 5.2.9 on 2026-01-15 14:17

import cintafactory.seaweedfs_storage
import diagrams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_remove_diagram_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cintafactory.seaweedfs_storage.SeaweedFSStorage(), upload_to=diagrams.models.thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='likec4file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
