# Generated by Django 5.2.9 on 2026-01-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0004_alter_diagram_thumbnail_alter_likec4file_id'),
        ('diagrams', '0004_likec4_png_metadata'),
    ]

    operations = [
    ]
