# Generated by Django 5.2.9 on 2026-02-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dat", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatViewflowProcess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewflow_process",
                        to="dat.dat",
                    ),
                ),
                (
                    "process_id",
                    models.UUIDField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "dat_viewflow_process",
                "verbose_name": "DAT Viewflow process",
                "verbose_name_plural": "DAT Viewflow processes",
            },
        ),
    ]
