# Base Python 3.12 (Debian Bookworm)
FROM python:3.12-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev curl netcat-traditional \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Installer deps Python
COPY requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip && pip install -r requirements.txt

# Copier le code du projet (le repo complet est rsync côté CI)
COPY . /app

# Entrypoint (migrations, collectstatic, etc.)
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh



# Gunicorn par défaut
ENV PORT=8000
EXPOSE 8000

CMD ["/entrypoint.sh"]
