# Base Python 3.12 (Debian Bookworm)
FROM python:3.12-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_NO_CACHE=1 \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:/root/.local/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev curl netcat-traditional \
 && rm -rf /var/lib/apt/lists/*

# Installer uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

WORKDIR /app

# Installer deps Python
COPY pyproject.toml uv.lock /app/
RUN uv sync --frozen --no-dev

# Copier le code du projet (le repo complet est rsync côté CI)
COPY . /app

# Entrypoint (migrations, collectstatic, etc.)
COPY cintafactory/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh



# Gunicorn par défaut
ENV PORT=8000
EXPOSE 8000

CMD ["/entrypoint.sh"]
