# Generated by Django 5.2.9 on 2026-01-26 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dat', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification message',
                'verbose_name_plural': 'Notification messages',
                'db_table': 'workflow_notification_message',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification type',
                'verbose_name_plural': 'Notification types',
                'db_table': 'workflow_notification_type',
                'ordering': ['title', 'level', 'pk'],
                'unique_together': {('title', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('created_by_display', models.CharField(blank=True, max_length=255)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='dat.dat')),
                ('notification_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_notifications', to='workflows.notificationmessage')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_notifications', to='workflows.notificationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_user_notification',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflow_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(help_text='Code stored on the target object to represent this step', max_length=64)),
                ('is_initial', models.BooleanField(default=False, help_text='Whether this step is the default/start of the workflow.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow step',
                'verbose_name_plural': 'Workflow steps',
                'db_table': 'workflow_step',
                'ordering': ['order', 'pk'],
                'unique_together': {('workflow', 'key'), ('workflow', 'state')},
            },
        ),
        migrations.CreateModel(
            name='HistoryNotificationSeen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_seen_by', to='dat.dathistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history_notifications_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow history seen',
                'verbose_name_plural': 'Workflow history seen',
                'db_table': 'workflow_history_notification_seen',
                'ordering': ['-seen_at', '-pk'],
                'unique_together': {('user', 'history')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_permissions', to='users.role')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='workflows.workflowstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow step permission',
                'verbose_name_plural': 'Workflow step permissions',
                'db_table': 'workflow_step_permission',
                'ordering': ['step', 'permission_type', 'role__name', 'user__username'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__isnull', False), ('user__isnull', False), _connector='OR'), name='workflow_step_permission_role_or_user'), models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('step', 'permission_type', 'role'), name='workflow_step_permission_unique_role'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('step', 'permission_type', 'user'), name='workflow_step_permission_unique_user')],
            },
        ),
    ]
