# Generated by Django 5.2.9 on 2026-02-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='content',
            field=models.TextField(blank=True, default='', null=True, unique=True),
        ),
    ]
