# Generated by Django 5.2.8 on 2025-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
