# Generated by Django 5.2.5 on 2025-10-09 14:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Niveau de hierarchie. Plus la valeur est elevee, plus les privileges sont importants.')),
            ],
            options={
                'db_table': 'USER_ROLE',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='mot de passe')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='derniere connexion')),
                ('is_superuser', models.BooleanField(default=False, help_text="Indique que cet utilisateur dispose de tous les droits sans attribution explicite.", verbose_name='statut superutilisateur')),
                ('username', models.CharField(error_messages={'unique': "Un utilisateur avec ce nom d'utilisateur existe deja."}, help_text="Requis. 150 caracteres ou moins. Lettres, chiffres et @/./+/-/_ uniquement.", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="nom d'utilisateur")),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prenom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom de famille')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adresse email')),
                ('is_staff', models.BooleanField(default=False, help_text="Indique si l'utilisateur peut se connecter a ce site d'administration.", verbose_name='statut personnel')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si cet utilisateur doit etre considere comme actif. Deselectionnez cette option plutot que de supprimer les comptes.", verbose_name='actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text="Groupes auxquels appartient cet utilisateur. Il herite des permissions accordees a chacun de ses groupes.", related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissions specifiques pour cet utilisateur.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='permissions utilisateur')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
