# Generated by Django 5.2.9 on 2026-01-26 12:36

import cintafactory.storage.seaweedfs_storage
import django.contrib.auth.models
import django.contrib.auth.validators
from django.contrib.auth.hashers import make_password
import django.db.models.deletion
import django.utils.timezone
import users.profile_pictures
import uuid
from django.conf import settings
from django.db import migrations, models

DEFAULT_PASSWORD = "123+Aze"
SUPERUSER_USERNAME = "super_admin"
SUPERUSER_EMAIL = "super_admin@example.com"

ROLE_DATA = (
    {"name": "Porteur de la demande", "slug": "porteur-demande"},
    {"name": "Architecte Référent", "slug": "architecte-referent"},
    {"name": "Architecte Technique", "slug": "architecte-technique"},
    {"name": "Urbaniste", "slug": "urbaniste"},
    {"name": "Analyste Sécu", "slug": "analyste-secu"},
    {"name": "RSSI", "slug": "rssi"},
    {"name": "Comité de validation", "slug": "comite-validation"},
    {"name": "Infra / Exploitation", "slug": "infra-exploitation"},
)

TECHNICAL_DIRECTIONS = (
    ("urbanisme", "Urbanisme"),
    ("architecture-technique", "Architecture technique"),
    ("cybersecurite", "Cybersécurité"),
    ("exploitations", "Exploitations"),
    ("besoins", "Besoins"),
)

DEFAULT_BUSINESS_DIRECTION = {
    "slug": "direction-metier-defaut",
    "name": "Direction métier par défaut",
}


def seed_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    for data in ROLE_DATA:
        Role.objects.update_or_create(slug=data["slug"], defaults=data)


def create_super_admin(apps, schema_editor):
    User = apps.get_model("users", "User")

    if not User.objects.filter(username=SUPERUSER_USERNAME).exists():
        User.objects.create(
            username=SUPERUSER_USERNAME,
            email=SUPERUSER_EMAIL,
            is_active=True,
            is_staff=True,
            is_superuser=True,
            password=make_password(DEFAULT_PASSWORD),
        )


def seed_technical_directions_and_groups(apps, schema_editor):
    TechnicalDirection = apps.get_model("users", "TechnicalDirection")
    BusinessGroup = apps.get_model("users", "BusinessGroup")
    BusinessDirection = apps.get_model("users", "BusinessDirection")
    User = apps.get_model("users", "User")

    direction_map = {}
    for slug, label in TECHNICAL_DIRECTIONS:
        direction, _ = TechnicalDirection.objects.get_or_create(
            slug=slug,
            defaults={"name": label},
        )
        if direction.name != label:
            direction.name = label
            direction.save(update_fields=["name"])
        direction_map[slug] = direction

    business_direction, _ = BusinessDirection.objects.get_or_create(
        slug=DEFAULT_BUSINESS_DIRECTION["slug"],
        defaults={"name": DEFAULT_BUSINESS_DIRECTION["name"]},
    )

    responsible = (
        User.objects.filter(is_superuser=True).order_by("id").first()
        or User.objects.order_by("id").first()
    )
    if not responsible:
        return

    for direction in direction_map.values():
        group = (
            BusinessGroup.objects.filter(direction=direction, is_default=True)
            .order_by("id")
            .first()
        )
        if group:
            updates = []
            if not group.is_default:
                group.is_default = True
                updates.append("is_default")
            if group.responsible_id != responsible.id:
                group.responsible = responsible
                updates.append("responsible")
            if not group.business_direction_id:
                group.business_direction = business_direction
                updates.append("business_direction")
            if updates:
                group.save(update_fields=updates)
            continue

        base_name = f"{direction.name} - Groupe par défaut"
        name = base_name
        counter = 2
        while BusinessGroup.objects.filter(name=name).exists():
            name = f"{base_name} {counter}"
            counter += 1

        BusinessGroup.objects.create(
            name=name,
            direction=direction,
            responsible=responsible,
            is_default=True,
            business_direction=business_direction,
        )


def assign_default_business_group(apps, schema_editor):
    BusinessGroup = apps.get_model("users", "BusinessGroup")
    User = apps.get_model("users", "User")

    default_group = (
        BusinessGroup.objects.filter(direction__slug="besoins", is_default=True)
        .order_by("id")
        .first()
        or BusinessGroup.objects.filter(is_default=True).order_by("id").first()
        or BusinessGroup.objects.order_by("id").first()
    )
    if not default_group:
        return

    User.objects.filter(
        business_group__isnull=True,
        role__technical_direction__isnull=False,
    ).update(business_group=default_group)


def create_role_users(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")
    BusinessGroup = apps.get_model("users", "BusinessGroup")

    default_group = (
        BusinessGroup.objects.filter(direction__slug="besoins", is_default=True)
        .order_by("id")
        .first()
        or BusinessGroup.objects.filter(is_default=True).order_by("id").first()
        or BusinessGroup.objects.order_by("id").first()
    )
    if not default_group:
        return

    password_hash = make_password(DEFAULT_PASSWORD)
    for role in Role.objects.all():
        existing_user = User.objects.filter(role=role).first()
        if existing_user:
            if role.technical_direction_id and not existing_user.business_group_id:
                existing_user.business_group = default_group
                existing_user.save(update_fields=["business_group"])
            continue

        base_username = f"{role.slug.replace('-', '_')}_user"
        username = base_username
        counter = 1
        while User.objects.filter(username=username).exists():
            username = f"{base_username}{counter}"
            counter += 1

        user_kwargs = {
            "username": username,
            "email": f"{username}@example.com",
            "role": role,
            "is_active": True,
            "password": password_hash,
        }
        if role.technical_direction_id:
            user_kwargs["business_group"] = default_group
        User.objects.create(**user_kwargs)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'BUSINESS_METIER_DIRECTION',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_admin_role', models.BooleanField(default=False, help_text='Les rôles administrateurs ne sont pas rattachés à une direction technique.')),
            ],
            options={
                'db_table': 'USER_ROLE',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TECHNICAL_DIRECTION',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=cintafactory.storage.seaweedfs_storage.SeaweedFSStorage(), upload_to=users.profile_pictures.build_profile_picture_storage_name)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('business_direction', models.ForeignKey(blank=True, help_text='Direction métier associée à ce groupe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_groups', to='users.businessdirection')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_groups', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.technicaldirection')),
            ],
            options={
                'db_table': 'BUSINESS_GROUP',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='business_group',
            field=models.ForeignKey(blank=True, help_text="Groupe métier auquel appartient l'utilisateur.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.businessgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='technical_direction',
            field=models.ForeignKey(blank=True, help_text='Direction technique associée à ce rôle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='users.technicaldirection'),
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=40)),
                ('scope', models.TextField(blank=True)),
                ('raw_profile', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_oauth_account',
                'ordering': ['provider', 'id'],
                'indexes': [models.Index(fields=['provider', 'email'], name='user_oauth__provide_03e1e1_idx'), models.Index(fields=['user', 'provider'], name='user_oauth__user_id_a04762_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='businessgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('direction',), name='unique_default_group_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='businessgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('business_direction__isnull', False)), fields=('business_direction', 'direction'), name='unique_business_direction_group_per_technical_direction'),
        ),
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
        migrations.RunPython(create_super_admin, migrations.RunPython.noop),
        migrations.RunPython(seed_technical_directions_and_groups, migrations.RunPython.noop),
        migrations.RunPython(assign_default_business_group, migrations.RunPython.noop),
        migrations.RunPython(create_role_users, migrations.RunPython.noop),
    ]
