# Generated by Django 5.2.5 on 2025-10-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_roles'),
    ]

    operations = [
    ]
