# Generated by Django 5.2.9 on 2026-01-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oauth_account'),
        ('users', '0005_realign_user_groups_with_roles'),
    ]

    operations = [
    ]
