# Generated by Django 5.2.9 on 2026-01-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260113_0943'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='user_oauth__provide_03e1e1_idx',
            old_name='user_oauth_account_provider_email_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='user_oauth__user_id_a04762_idx',
            old_name='user_oauth_account_user_provider_idx',
        ),
    ]
