version: "3.9"

services:
  likec4:
    image: likec4-cli
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRAPHVIZ_VERSION: ${GRAPHVIZ_VERSION:-}
        PLAYWRIGHT_VER: ${PLAYWRIGHT_VER:-}
        LIKEC4_VER: ${LIKEC4_VER:-}
    entrypoint: ["/bin/sh", "-c"]
    command: ["node server.js & mkdir -p ${LIKEC4_PREVIEW_DIR:-/tmp/likec4-previews} && touch ${LIKEC4_PREVIEW_DIR:-/tmp/likec4-previews}/bootstrap.c4 && /usr/local/bin/likec4 dev ${LIKEC4_PREVIEW_DIR:-/tmp/likec4-previews} --host 0.0.0.0"]
    volumes:
      - ./:/data
    environment:
      - C4_FILE=likec4/default.c4
      - LIKEC4_PREVIEW_DIR=/tmp/likec4-previews
      - LIKEC4_API_TOKEN=${LIKEC4_API_TOKEN:-}
