"""
Django settings for cintafactory project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-m3*wk1omhr%_7ky#c^s9i6&q@f$19+y&1-lh^1b)+tm$hcz+s1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

def _split_env_list(value: str | None, default: str = "") -> list[str]:
    raw = value if value is not None else default
    return [item.strip() for item in raw.split(",") if item.strip()]


_allowed_hosts_raw = os.environ.get("ALLOWED_HOSTS")
if _allowed_hosts_raw is None:
    _allowed_hosts_raw = os.environ.get("DJANGO_ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = _split_env_list(_allowed_hosts_raw, default="*")
ALLOWED_HOSTS=["*"]
_csrf_env_raw = os.environ.get("CSRF_TRUSTED")
if _csrf_env_raw is None:
    _csrf_env_raw = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
_csrf_trusted_env = _split_env_list(_csrf_env_raw)


def _build_csrf_trusted_origins(hosts: list[str]) -> set[str]:
    origins: set[str] = set()
    for host in hosts:
        if host in {"*", ""} or host.startswith("."):
            # Wildcard entries are invalid for CSRF trusted origins.
            continue
        if "://" in host:
            origins.add(host)
        else:
            origins.add(f"http://{host}")
            origins.add(f"https://{host}")
    return origins


CSRF_TRUSTED_ORIGINS = sorted(
    _build_csrf_trusted_origins(_csrf_trusted_env)
    | _build_csrf_trusted_origins(ALLOWED_HOSTS)
)
# Application STATIC_URL 

INSTALLED_APPS = [
    "material",
    "material.frontend",

    "viewflow",

    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your apps
    "diagrams.apps.DiagramsConfig",
    "workflows.apps.WorkflowsConfig",
    "users.apps.UsersConfig",
    "dat.apps.DatConfig",
    "account.apps.AccountConfig",

]

AUTH_USER_MODEL = "users.User"

LOGIN_REDIRECT_URL = "/account/profile/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "cintafactory.middleware.LoggingContextMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'cintafactory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / "templates",
                 PROJECT_DIR / "templates",
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "material.frontend.context_processors.modules",
            ],
        },
    },
]

WSGI_APPLICATION = 'cintafactory.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME", os.environ.get("POSTGRES_DB", "")),
        "USER": os.environ.get("DATABASE_USER", os.environ.get("POSTGRES_USER", "")),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", os.environ.get("POSTGRES_PASSWORD", "")),
        "HOST": os.environ.get("DATABASE_HOST", "db"),
        "PORT": os.environ.get("DATABASE_PORT", "5432"),
        # "OPTIONS": {"sslmode": "prefer"}, if needed in external prod DB
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles"))

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", BASE_DIR / "media"))

# Content Security Policy (effective when django-csp is installed)
CSP_FRAME_SRC = ["'self'", "https://embed.diagrams.net"]
CSP_CONNECT_SRC = ["'self'", "https://embed.diagrams.net"]
CSP_IMG_SRC = ["'self'", "data:", "blob:"]
CSP_SCRIPT_SRC = ["'self'"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Observability / logging
LOGGING_CONFIG = "logging.config.dictConfig"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO").upper(),
    },
}
