"""
Django settings for cintafactory project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

from dotenv import load_dotenv

from .logging_utils import build_logging_dict

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = Path(__file__).resolve().parent

load_dotenv(BASE_DIR / ".env", override=False)
load_dotenv(BASE_DIR.parent / ".env", override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-m3*wk1omhr%_7ky#c^s9i6&q@f$19+y&1-lh^1b)+tm$hcz+s1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

def _split_env_list(value: str | None, default: str = "") -> list[str]:
    raw = value if value is not None else default
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = ["*"]
_csrf_env_raw = os.environ.get("CSRF_TRUSTED")
if _csrf_env_raw is None:
    _csrf_env_raw = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
_csrf_trusted_env = _split_env_list(_csrf_env_raw)


def _build_csrf_trusted_origins(hosts: list[str]) -> set[str]:
    origins: set[str] = set()
    for host in hosts:
        if host in {"*", ""} or host.startswith("."):
            # Wildcard entries are invalid for CSRF trusted origins.
            continue
        if "://" in host:
            origins.add(host)
        else:
            origins.add(f"http://{host}")
            origins.add(f"https://{host}")
    return origins


CSRF_TRUSTED_ORIGINS = sorted(
    _build_csrf_trusted_origins(_csrf_trusted_env)
    | _build_csrf_trusted_origins(ALLOWED_HOSTS)
)

# Honour reverse-proxy HTTPS headers so absolute URLs use the correct scheme.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Application STATIC_URL 

INSTALLED_APPS = [
    "material",
    "material.frontend",

    "viewflow",

    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "oauth2_provider",

    # Your apps
    "diagrams.apps.DiagramsConfig",
    "workflows.apps.WorkflowsConfig",
    "users.apps.UsersConfig",
    "dat.apps.DatConfig",
    "account.apps.AccountConfig",
    "configuration.apps.ConfigurationConfig",

]

AUTH_USER_MODEL = "users.User"

LOGIN_REDIRECT_URL = "/account/profile/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "cintafactory.middleware.LoggingContextMiddleware",
    "cintafactory.middleware.DynamicCsrfTrustedOriginsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "cintafactory.storage.WhiteNoiseStaticFilesStorage"
WHITENOISE_USE_FINDERS = True

ROOT_URLCONF = 'cintafactory.urls'

# Allow same-origin iframes (draw.io embed) while still blocking third-party framing.
X_FRAME_OPTIONS = "SAMEORIGIN"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / "templates",
                PROJECT_DIR / "templates",
                BASE_DIR / "cintafactory" / "templates",
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "material.frontend.context_processors.modules",
                "workflows.context_processors.workflow_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = 'cintafactory.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME", os.environ.get("POSTGRES_DB", "")),
        "USER": os.environ.get("DATABASE_USER", os.environ.get("POSTGRES_USER", "")),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", os.environ.get("POSTGRES_PASSWORD", "")),
        "HOST": os.environ.get("DATABASE_HOST", "db"),
        "PORT": os.environ.get("DATABASE_PORT", "5432"),
        # "OPTIONS": {"sslmode": "prefer"}, if needed in external prod DB
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles"))

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", BASE_DIR / "media"))

SEAWEEDFS_FILER_URL = os.getenv("SEAWEEDFS_FILER_URL", "http://seaweedfs:8888").rstrip("/")
SEAWEEDFS_PUBLIC_URL = os.getenv("SEAWEEDFS_PUBLIC_URL", SEAWEEDFS_FILER_URL).rstrip("/")
SEAWEEDFS_PUBLIC_URL_PP = os.getenv("SEAWEEDFS_PUBLIC_URL_PP", "http://localhost:8888").rstrip("/")
SEAWEEDFS_BASE_DIR = os.getenv("SEAWEEDFS_BASE_DIR", "media").strip("/")
SEAWEEDFS_TIMEOUT = int(os.getenv("SEAWEEDFS_TIMEOUT", "30"))
LIKEC4_METADATA_TOKEN = os.getenv("LIKEC4_METADATA_TOKEN", "")

CLAMAV_HOST = os.getenv("CLAMAV_HOST", "clamav")
CLAMAV_PORT = int(os.getenv("CLAMAV_PORT", "3310"))
CLAMAV_TIMEOUT = int(os.getenv("CLAMAV_TIMEOUT", "30"))
CLAMAV_RETRY_COUNT = int(os.getenv("CLAMAV_RETRY_COUNT", "5"))
CLAMAV_RETRY_DELAY = float(os.getenv("CLAMAV_RETRY_DELAY", "1.0"))
CLAMAV_SCAN_DIR = os.getenv("CLAMAV_SCAN_DIR", "/clamav_scan")

OAUTH_HTTP_TIMEOUT = int(os.getenv("OAUTH_HTTP_TIMEOUT", "10"))
OAUTH_ALLOW_EMAIL_LINKING = os.getenv("OAUTH_ALLOW_EMAIL_LINKING", "1").lower() in {"1", "true", "yes", "on"}
MICROSOFT_OAUTH_TENANT_ID = os.getenv("MICROSOFT_OAUTH_TENANT_ID", "common").strip() or "common"
OKTA_OAUTH_DOMAIN = os.getenv("OKTA_OAUTH_DOMAIN", "").rstrip("/")
OAUTH_PROVIDERS = {
    "google": {
        "label": "Google",
        "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "userinfo_url": "https://openidconnect.googleapis.com/v1/userinfo",
        "scopes": ("openid", "email", "profile"),
        "extra_authorize_params": {
            "access_type": "offline",
            "prompt": "consent",
            "include_granted_scopes": "true",
        },
    },
    "microsoft": {
        "label": "Microsoft",
        "client_id": os.getenv("MICROSOFT_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("MICROSOFT_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": f"https://login.microsoftonline.com/{MICROSOFT_OAUTH_TENANT_ID}/oauth2/v2.0/authorize",
        "token_url": f"https://login.microsoftonline.com/{MICROSOFT_OAUTH_TENANT_ID}/oauth2/v2.0/token",
        "userinfo_url": "https://graph.microsoft.com/oidc/userinfo",
        "scopes": ("openid", "email", "profile"),
        "extra_authorize_params": {},
    },
    "amazon": {
        "label": "Amazon",
        "client_id": os.getenv("AMAZON_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("AMAZON_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": "https://www.amazon.com/ap/oa",
        "token_url": "https://api.amazon.com/auth/o2/token",
        "userinfo_url": "https://api.amazon.com/user/profile",
        "scopes": ("profile", "profile:user_id"),
        "extra_authorize_params": {},
        "userinfo_mapping": {
            "user_id": "user_id",
            "email": "email",
            "full_name": "name",
        },
    },
    "okta": {
        "label": "Okta",
        "client_id": os.getenv("OKTA_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("OKTA_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": f"{OKTA_OAUTH_DOMAIN}/oauth2/default/v1/authorize" if OKTA_OAUTH_DOMAIN else "",
        "token_url": f"{OKTA_OAUTH_DOMAIN}/oauth2/default/v1/token" if OKTA_OAUTH_DOMAIN else "",
        "userinfo_url": f"{OKTA_OAUTH_DOMAIN}/oauth2/default/v1/userinfo" if OKTA_OAUTH_DOMAIN else "",
        "scopes": ("openid", "email", "profile"),
        "extra_authorize_params": {},
    },
    "cintamaya": {
        "label": "Cintamaya",
        "client_id": os.getenv("CINTAMAYA_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("CINTAMAYA_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": "https://auth.CINTAMAYA.com/authorize",
        "token_url": "https://auth.CINTAMAYA.com/token",
        "userinfo_url": "https://auth.CINTAMAYA.com/userinfo",
        "scopes": ("openid", "email", "profile"),
        "extra_authorize_params": {},
    },
    "riot": {
        "label": "Riot Games",
        "client_id": os.getenv("RIOT_OAUTH_CLIENT_ID", ""),
        "client_secret": os.getenv("RIOT_OAUTH_CLIENT_SECRET", ""),
        "authorize_url": "https://auth.riotgames.com/authorize",
        "token_url": "https://auth.riotgames.com/token",
        "userinfo_url": "https://auth.riotgames.com/userinfo",
        "scopes": ("openid", "email", "profile"),
        "extra_authorize_params": {},
    }
}

DRAWIO_BASE_URL = os.getenv("DRAWIO_BASE_URL", "http://drawio:8080").rstrip("/")
if not DRAWIO_BASE_URL:
    DRAWIO_BASE_URL = "http://drawio:8080"

DRAWIO_PUBLIC_URL = os.getenv("DRAWIO_PUBLIC_URL", DRAWIO_BASE_URL).rstrip("/")
if not DRAWIO_PUBLIC_URL:
    DRAWIO_PUBLIC_URL = DRAWIO_BASE_URL

DRAWIO_LIBS = os.getenv("DRAWIO_LIBS", "general").strip() or "general"
DRAWIO_CLIBS = tuple(
    item.strip()
    for item in os.getenv("DRAWIO_CLIBS", "").split(",")
    if item.strip()
)
DRAWIO_EXPORT_URL = "http://drawio-export:8000/export"

def _origin_from_url(url: str) -> str:
    parts = urlsplit(url)
    if parts.scheme and parts.netloc:
        return f"{parts.scheme}://{parts.netloc}"
    return url


DRAWIO_PUBLIC_ORIGIN = _origin_from_url(DRAWIO_PUBLIC_URL)

# Content Security Policy (effective when django-csp is installed)
CSP_FRAME_SRC = ["'self'", DRAWIO_PUBLIC_ORIGIN]
CSP_CONNECT_SRC = ["'self'", DRAWIO_PUBLIC_ORIGIN]
CSP_IMG_SRC = ["'self'", "data:", "blob:"]
CSP_SCRIPT_SRC = ["'self'"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Observability / logging
LOGGING_CONFIG = "cintafactory.logging_utils.configure_logging"
LOGGING = build_logging_dict(BASE_DIR)
