name: SBOM & Vulnerabilitées Scan

on:
  pull_request:
    branches: [ main , dev ]

jobs:
  scan:
    runs-on: [ self-hosted ]

    steps:

      - name: Initialisation de variables
        run: |
          echo "RAPPORT_PATH=/home/debian/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "SCRIPT_PATH=/home/debian/script/blocage-grype.py" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "RAPPORT_PATH=$RAPPORT_PATH"
          echo "SCRIPT_PATH=$SCRIPT_PATH"

      # Récupère le code source du repo sur le runner
      - name: Importation du repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
        with:
          clean: true

      # Génère la date du jour      
      - name: Génération de la Date
        run: echo "DATE=$(date +%d-%m-%Y)" >> "$GITHUB_ENV"

      # Création des dossier /nom du repo/syft et /nom du repo/grype s'ils sont inexistant
      - name : Création des dossiers de destinations
        run: mkdir -p $RAPPORT_PATH/syft $RAPPORT_PATH/grype/txt $RAPPORT_PATH/grype/json $RAPPORT_PATH/grant

      # Génération SBOM
      - name: Génération du SBOM
        run: |
          syft dir:. -o cyclonedx-json > $RAPPORT_PATH/syft/${DATE}_SBOM.json

      # Mise à jour de la base de donnée Grype 
      - name: Mise à jour de la db Grype
        run : grype db update

      # Recherche les vulnérabilites associées au sbom
      - name: Scan vulnerabilities with Grype
        run: |
          grype sbom:$RAPPORT_PATH/syft/${DATE}_SBOM.json -o table > $RAPPORT_PATH/grype/txt/${DATE}_SCA.txt
          grype sbom:$RAPPORT_PATH/syft/${DATE}_SBOM.json -o json > $RAPPORT_PATH/grype/json/${DATE}_SCA.json

      # Vérification de compliance avec grant
      - name: Vérifier les licences
        run: |
           grant list $RAPPORT_PATH/syft/${DATE}_SBOM.json > $RAPPORT_PATH/grant/${DATE}_LICENCE.txt

      # Utilisation du script pour vérifier la cévérité des CVEs 
      - name: Utilisation du script pour bloquer ou non. 
        run: |
           python3 $SCRIPT_PATH $RAPPORT_PATH/grype/json/${DATE}_SCA.json
