name: Check code
on:
  push:
    branches: [ dev-mat ]

permissions:
  contents: read   

jobs:
#-------------------------------------------------------------------------------------
#                                    GITLEAKS SCAN
#-------------------------------------------------------------------------------------
  gitleaks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Importation du repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
      
      - name: lancement du scan
        id: Gitleaks
        run: |
          docker run --rm -v ${{ github.workspace }}:/code ghcr.io/gitleaks/gitleaks:latest detect --source="/code" --log-opts="-1" --verbose --report-format=json --report-path="hadolint.json"
          touch "hadolint.json"
        continue-on-error: true
      
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: hadolint-report
          path: hadolint.json
#-------------------------------------------------------------------------------------
#                                    SBOM SCAN
#-------------------------------------------------------------------------------------
  sbom_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Importation du repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
      
      - name: Syft
        id: Syft
        run : |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft dir:. -o cyclonedx-json@1.5="${{ env.DATE }}_SBOM.json" --select-catalogers "-python-package-cataloger" --source-name "${{ github.event.repository.name }}" --source-version "${{ github.sha }}"

      - name: Grype json
        id: GrypeJson
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          sbom: ${{ env.DATE }}_SBOM.json
          fail-build: false
          output-format: json
          output-file: ${{ env.DATE }}_SCA.json

      - name: Grype txt
        id: GrypeTxt
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype sbom:${{ env.DATE }}_SBOM.json -o table > ${{ env.DATE }}_SCA.txt
      
      - name: Grant
        id: Grant
        continue-on-error: true
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grant/main/install.sh | sh -s -- -b /usr/local/bin
          grant check ${{ env.DATE }}_SBOM.json > ${{ env.DATE }}_LICENCE.txt
          mkdir -p reports && mv ${{ env.DATE }}_SBOM.json reports && mv ${{ env.DATE }}_SCA.json reports && mv ${{ env.DATE }}_SCA.txt reports && mv ${{ env.DATE }}_LICENCE.txt reports

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: sbom-reports
          path: reports/
          
#-------------------------------------------------------------------------------------
#                                    SonarQube SCAN
#-------------------------------------------------------------------------------------       
  SonarQube:
    runs-on: ubuntu-latest
    
    steps:
      - name: Importation du repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
      
      - name: SonarQube
        id: SonarQube
        uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # 8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Cintafactory-dev
            -Dsonar.projectName="Cintafactory"
#-------------------------------------------------------------------------------------
#                                    Hadolint SCAN
#-------------------------------------------------------------------------------------
  Hadolint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Importation du repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # 4.3.1
      
      - name: Hadolint
        id: Hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: dockerfile
          no-fail: true
      
      - name: Envoie des rapports
        run: 

