name: "EKS Ephemeral Infra"

on:
  push:
    branches:
      - dev-Abd
    paths:
      - "terraform/**"
      - ".github/workflows/infra-eks.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Execution"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Authentification AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::512584596480:role/github-actions-eks-role
          aws-region: eu-west-3

      - name: Installation de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # Exécute l'apply directement pour tester la création
      - name: Terraform Apply
        run: terraform apply -auto-approve